### ISSUE TITLE
how to install the geekplanet?

### ISSUE THREAD

**Issue by dchcm** [r3dDoX/geekplanet#1185]
Hi,

I just find out the great webshop created, and interesting to have a copy of geekplanet as an family shop online for my family, could you help me how to install to the hosting? Ở any instruction here for the new who don't know much about code.

if there have a service to install the code to the hosting, pls tell me too, i would like to pay for having an live shop of the geekplanet. Thanks

**Comment by r3dDoX** [comment]
Hey

Nice to hear you stumbled over my shop. Unfortunately this is probably not what you‘re looking for. It‘s actually meant as a base to start programming your own shop. So now tier you could buy or directly deploy.

What might suit you more are solutions from wix.com or similar. Hope you find the right tool for your need.

Regards Patrick
